---

- name: Run Kafka Debugger
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: "{{ kafka_broker | default('localhost') }}"
        port: "{{ kafka_port | default(9092) }}"
        cafile: "{{ eda.filename.cafile }}"
        security_protocol: "{{ kafka_security_protocol | default('PLAINTEXT') }}"
        sasl_mechanism: "{{ kafka_sasl_mechanism }}"
        sasl_plain_username: "{{ kafka_username}}"
        sasl_plain_password: "{{ kafka_password }}"
        topics:
          - "{{ kafka_topic | default('eda') }}"
        check_hostname: "{{ kafka_ssl_check_hostname | default(false) }}"
        group_id: "ansible-{{ kafka_topic | default('eda') }}-group"

  rules:
    - name: "When a message is received on topic 'eda', print its content"
      condition: event.body is defined
      actions:
        - debug:
            msg: "Received message on topic 'eda': {{ event }}"

        - run_job_template:
            name: eda-kafka-debugger-playbook
            wait: false
            organization: "OCP"
